name = "aicompass"
compatibility_date = "2024-01-01"

[env.production]
compatibility_date = "2024-01-01"

[[env.production.routes]]
pattern = "*"
zone_name = "your-domain.com"  # Replace with your actual domain if you have one 